# ------------------------------------------------------------------------------
# USB EPROM/Flash Programmer
#
# Copyright (2024) Robson Martins
#
# This work is licensed under a Creative Commons Attribution-NonCommercial-
# ShareAlike 4.0 International License.
# ------------------------------------------------------------------------------
name: Update Software Doc

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  SOFTWARE_PROJECT_DIR: ${{github.workspace}}/software/usbflashprog

jobs:
  build:
    name: Update Software Doc
    runs-on: ubuntu-latest

    steps:
    # ------------------------------------------------------------------------
    # Checkout the sources
    # ------------------------------------------------------------------------
    - name: Checkout the Sources
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    # ------------------------------------------------------------------------
    # Install Prerequisites (Linux)
    # ------------------------------------------------------------------------
    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install cmake build-essential libglu1-mesa-dev libpulse-dev libglib2.0-dev lcov doxygen graphviz
        sudo apt-get --no-install-recommends install libqt*5-dev qt*5-dev libqt5waylandcompositor5-dev

    # ------------------------------------------------------------------------
    # Configure CMake
    # ------------------------------------------------------------------------
    - name: Configure CMake
      working-directory: ${{env.SOFTWARE_PROJECT_DIR}}
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_BUILD=ON

    # ------------------------------------------------------------------------
    # Build
    # ------------------------------------------------------------------------
    - name: Build
      working-directory: ${{env.SOFTWARE_PROJECT_DIR}}
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    # ------------------------------------------------------------------------
    # Test
    # ------------------------------------------------------------------------
    - name: Test
      working-directory: ${{env.SOFTWARE_PROJECT_DIR}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    # ------------------------------------------------------------------------
    # Coverage
    # ------------------------------------------------------------------------
    - name: Coverage
      working-directory: ${{env.SOFTWARE_PROJECT_DIR}}
      run: |
        rm -Rf ${{env.SOFTWARE_PROJECT_DIR}}/../../docs/software/lcov/
        lcov --directory ${{env.SOFTWARE_PROJECT_DIR}}/build/ --capture --output-file ${{env.SOFTWARE_PROJECT_DIR}}/build/coverage.info -rc lcov_branch_coverage=1 --exclude \/usr\/include\/\* --exclude \/usr\/local\/include\/\* --exclude ${{env.SOFTWARE_PROJECT_DIR}}\/build\/\* --exclude ${{env.SOFTWARE_PROJECT_DIR}}\/test\/\* --exclude ${{env.SOFTWARE_PROJECT_DIR}}\/\*\.h\*
        genhtml --prefix ${{env.SOFTWARE_PROJECT_DIR}} --ignore-errors source ${{env.SOFTWARE_PROJECT_DIR}}/build/coverage.info --legend --title \"`git rev-parse --short HEAD`\" --output-directory ${{env.SOFTWARE_PROJECT_DIR}}/../../docs/software/lcov/

    # ------------------------------------------------------------------------
    # Doxygen
    # ------------------------------------------------------------------------
    - name: Doxygen
      working-directory: ${{env.SOFTWARE_PROJECT_DIR}}
      run: |
        rm -Rf ${{env.SOFTWARE_PROJECT_DIR}}/../../docs/software/html/
        doxygen

    # ------------------------------------------------------------------------
    # Commit
    # ------------------------------------------------------------------------
    - name: Commit Files
      run: |
        git config --local user.email "noreply-github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/software/
        git commit -m "Update Software Documentation" -a

    # ------------------------------------------------------------------------
    # Push
    # ------------------------------------------------------------------------
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
